_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 8
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  ROI_BOX_HEAD:
    POOLER_SAMPLING_RATIO: 2
    NUM_CONV: 4
  ROI_MASK_HEAD:
    POOLER_SAMPLING_RATIO: 2
SOLVER:
  BASE_LR: 0.02 # diff
  CHECKPOINT_PERIOD: 1000
  GAMMA: 0.1
  IMS_PER_BATCH: 12
  MAX_ITER: 24000 # diff
  MOMENTUM: 0.9
  STEPS: # diff
  - 12000
  - 20000
  WARMUP_FACTOR: 0.03
  WARMUP_ITERS: 1000 # diff
  WARMUP_METHOD: "linear"
  WEIGHT_DECAY: 0.0001 # diff
  WEIGHT_DECAY_BIAS: 0.0
DATALOADER:
  NUM_WORKERS: 8
INPUT:
  MIN_SIZE_TRAIN:
  - 800
  - 832
  - 864
  - 896
  - 928
  - 960
  - 992
  - 1024
  - 1024
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TEST: 2048
  MAX_SIZE_TEST: 2048
