MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  META_ARCHITECTURE: "TensorMask"
  ROI_HEADS:
    NUM_CLASSES: 8
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  ANCHOR_GENERATOR:
    SIZES: [[44, 60], [88, 120], [176, 240], [352, 480], [704, 960], [1408, 1920]]
    ASPECT_RATIOS: [[1.0]]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    FUSE_TYPE: "avg"
  TENSOR_MASK:
    ALIGNED_ON: True
    BIPYRAMID_ON: True
SOLVER:
  IMS_PER_BATCH: 3 # test
  BASE_LR: 0.01
  STEPS: (21600, 28800,)
  MAX_ITER: 31500
VERSION: 2
INPUT:
  MIN_SIZE_TRAIN:
  - 800
  - 832
  - 864
  - 896
  - 928
  - 960
  - 992
  - 1024
  - 1024
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TEST: 720 # test
  MAX_SIZE_TEST: 1280 # test